// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

export const SUPABASE_ENV_CONFIGURED = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!SUPABASE_ENV_CONFIGURED) {
  console.error('Supabase env vars missing: defina VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Note: if envs estiverem faltando, cria um client inoperante (requisições vão falhar)
export const supabase = createClient<Database>(
  SUPABASE_URL || 'http://env-missing.supabase.local',
  SUPABASE_PUBLISHABLE_KEY || 'env-missing-key',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
